### ISSUE TITLE
OPENLIB_FA_INCLUDE-NOTFOUND

### ISSUE THREAD

**Issue by tdnet12434** [interaction-lab/openface_ros#2]
I already finished ``sudo make install `` after install openface and run some demo that work well.
But i failed to build this package due to missing OPENLIB_FA_INCLUDE.

I'm too new to modify cmake include path directly.
It will appreciate if you can guide me to do this directly or alternative solution.
Thank you advanced :)

**Comment by ziqiaojin** [comment]
Hey there, I had the same issue with you. then I found out that that I installed open face from a different repo, try to install the one provide by interaction-lab as stated in the remade, that worked out for me.

**Comment by tdnet12434** [comment]
That make sense! 
I will test and let you know soon.
Thank you for sharing solution sir :)

**Comment by tdnet12434** [comment]
It's work now!! Thank you again :) 
So i close this issue now.
